import assert from "node:assert/strict";
import { test } from "node:test";

import {
  createStoredImportedArchiveRecord,
  currentImportedArchiveKey,
  saveImportedArchiveRecord,
  clearImportedArchiveRecord,
} from "@serfbound/app";
import { parseDosPaCatalog } from "@serfbound/assets";

class MemoryImportedArchiveStore {
  record = null;

  async loadCurrent() {
    return this.record === null
      ? null
      : {
          ...this.record,
          bytes: this.record.bytes.slice(0),
        };
  }

  async saveCurrent(record) {
    this.record = {
      ...record,
      bytes: record.bytes.slice(0),
    };
  }

  async clearCurrent() {
    this.record = null;
  }
}

function createGeneratedPaArchive() {
  const bytes = new Uint8Array(24);
  const view = new DataView(bytes.buffer);
  view.setUint32(0, bytes.byteLength, true);
  view.setUint32(4, 1, true);
  view.setUint32(8, 8, true);
  view.setUint32(12, 16, true);
  return bytes;
}

test("imported archive records preserve metadata and clone generated bytes", () => {
  const sourceBytes = createGeneratedPaArchive();
  const record = createStoredImportedArchiveRecord({
    fileName: "SPAU.PA",
    normalizedName: "SPAU.PA",
    bytes: sourceBytes,
    importedAtIso: "2026-06-09T23:00:00.000Z",
  });

  sourceBytes.fill(0);

  assert.equal(record.schemaVersion, 1);
  assert.equal(record.storageKey, currentImportedArchiveKey);
  assert.equal(record.source, "dos-pa");
  assert.equal(record.fileName, "SPAU.PA");
  assert.equal(record.byteLength, 24);
  assert.equal(record.importedAtIso, "2026-06-09T23:00:00.000Z");
  assert.equal(parseDosPaCatalog(record.bytes).header.entryCount, 1);
});

test("imported archive store contract supports save, load, and clear", async () => {
  const store = new MemoryImportedArchiveStore();
  const record = createStoredImportedArchiveRecord({
    fileName: "SPAU.PA",
    normalizedName: "SPAU.PA",
    bytes: createGeneratedPaArchive(),
    importedAtIso: "2026-06-09T23:00:00.000Z",
  });

  assert.equal(await store.loadCurrent(), null);
  assert.deepEqual(await saveImportedArchiveRecord(store, record), {
    state: "persisted",
  });

  const loaded = await store.loadCurrent();
  assert.notEqual(loaded, null);
  assert.deepEqual(
    {
      ...loaded,
      bytes: Array.from(new Uint8Array(loaded.bytes)),
    },
    {
      ...record,
      bytes: Array.from(new Uint8Array(record.bytes)),
    },
  );

  assert.deepEqual(await clearImportedArchiveRecord(store), {
    state: "cleared",
  });
  assert.equal(await store.loadCurrent(), null);
});

test("storage operation helpers return recoverable error states", async () => {
  const failingStore = {
    async loadCurrent() {
      return null;
    },
    async saveCurrent() {
      throw new Error("quota exhausted");
    },
    async clearCurrent() {
      throw new Error("delete denied");
    },
  };
  const record = createStoredImportedArchiveRecord({
    fileName: "SPAU.PA",
    normalizedName: "SPAU.PA",
    bytes: createGeneratedPaArchive(),
  });

  assert.deepEqual(await saveImportedArchiveRecord(failingStore, record), {
    state: "error",
    message: "quota exhausted",
  });
  assert.deepEqual(await clearImportedArchiveRecord(failingStore), {
    state: "error",
    message: "delete denied",
  });
});
